# Tâche n°4:  Analyse cristallographique d’un matériau


   

1) Téléchargement de la structure du matériaux 

In [1]:
from pymatgen.ext.matproj import MPRester
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

with MPRester ("yDHrTj9RRkoKjTjOFwD0btKpsIOcE65N") as m:
    
    #Création de la structure du cristal à partir du MP
    structure = m.get_structure_by_material_id("mp-20072")



#Création d'un objet SpaceGroupAnalyzer
struct = SpacegroupAnalyzer(structure)
prim_struct = struct.get_primitive_standard_structure()

Retrieving MaterialsDoc documents:   0%|          | 0/1 [00:00<?, ?it/s]

2) Vecteur de base de ses réseaux direct 

Tout d'abord on va déterminer les différentes caractéristique de notre maille cristalline. A savoir a,b et c ainsi que alpha, beta et gamma de notre maille primitive. 

In [2]:

prim_lattice = prim_struct.lattice
print(f"Maille primitive: a = {prim_lattice.a:.3f} Å, b = {prim_lattice.a:.3f} Å, c = {prim_lattice.a:.3f} Å, α = {prim_lattice.alpha:.3f}°, β = {prim_lattice.beta:.3f}°, γ = {prim_lattice.gamma:.3f}° ")

Maille primitive: a = 6.055 Å, b = 6.055 Å, c = 6.055 Å, α = 37.029°, β = 37.029°, γ = 37.029° 


Ensuite, grâce aux différentes caractéristiques trouvées ci dessus on va pouvoir déterminer les vecteurs de base du réseau direct. 



In [3]:
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

# Récupération des caractéristiques de la maille cristalline
longueur_vecteur = 6.055
angle_lattice = 37.029


# comme on a que a=b=c et que α = β = γ ≠ 90° on peut utiliser la formule rhombohedral pour trouver les vecteurs de base 
matrice_vecteurs_directs = struct.find_primitive().lattice.rhombohedral(longueur_vecteur, angle_lattice).matrix


print("Base des vecteurs du réseau direct :")
print(matrice_vecteurs_directs)




Base des vecteurs du réseau direct :
[[3.64643709 0.         4.833893  ]
 [1.61875837 3.26743397 4.833893  ]
 [0.         0.         6.055     ]]


In [4]:
lattice = structure.lattice
print("Vecteurs du réseau direct :")
print(lattice.matrix)

Vecteurs du réseau direct :
[[ 5.74160558e+00 -1.92274365e+00 -4.12061000e-03]
 [ 5.74160558e+00  1.92274365e+00 -4.12061000e-03]
 [ 5.10006378e+00 -0.00000000e+00  3.26379283e+00]]


3. Vecteur de base de ses réseaux réciproque 

Les vecteurs de base du réseau réciproque sont donnés par :

$$
\mathbf{a}^* = \frac{2\pi}{V} (\mathbf{b} \times \mathbf{c})
$$

$$
\mathbf{b}^* = \frac{2\pi}{V} (\mathbf{c} \times \mathbf{a})
$$

$$
\mathbf{c}^* = \frac{2\pi}{V} (\mathbf{a} \times \mathbf{b})
$$

où \( V \) est le volume de la maille directe, donné par :

$$
V = \mathbf{a} \cdot (\mathbf{b} \times \mathbf{c})
$$

In [5]:
# Récupération du réseau réciproque
reciprocal = prim_struct.lattice.reciprocal_lattice

# Longueurs des vecteurs du réseau réciproque
a_r, b_r, c_r = reciprocal.a, reciprocal.b, reciprocal.c

# Angles du réseau réciproque
alpha_r, beta_r, gamma_r = reciprocal.alpha, reciprocal.beta, reciprocal.gamma

# Affichage des résultats
print(f"Longueurs des vecteurs du réseau réciproque : a* = {a_r:.3f} Å⁻¹, b* = {b_r:.3f} Å⁻¹, c* = {c_r:.3f} Å⁻¹")
print(f"Angles du réseau réciproque : α* = {alpha_r:.3f}°, β* = {beta_r:.3f}°, γ* = {gamma_r:.3f}°")


Longueurs des vecteurs du réseau réciproque : a* = 1.923 Å⁻¹, b* = 1.923 Å⁻¹, c* = 1.923 Å⁻¹
Angles du réseau réciproque : α* = 116.355°, β* = 116.355°, γ* = 116.355°


In [6]:
import numpy as np

# Matrice des vecteurs du réseau direct (de l'image 1)
direct_lattice_matrix = np.array([
    [3.64645571, 0, 4.83387583],
    [1.61876381, 3.26745206, 4.83387583],
    [0, 0, 6.0549972]
])

# Extraction des vecteurs du réseau direct
a_vec, b_vec, c_vec = direct_lattice_matrix

# Calcul du volume de la maille directe
V = np.dot(a_vec, np.cross(b_vec, c_vec))

# Calcul des vecteurs du réseau réciproque
a_star_vec = (2 * np.pi / V) * np.cross(b_vec, c_vec)
b_star_vec = (2 * np.pi / V) * np.cross(c_vec, a_vec)
c_star_vec = (2 * np.pi / V) * np.cross(a_vec, b_vec)

# Matrice des vecteurs du réseau réciproque
reciprocal_lattice_matrix = np.array([a_star_vec, b_star_vec, c_star_vec])

# Affichage des résultats
print("\nVecteurs de base du réseau réciproque :")
print(reciprocal_lattice_matrix)


Vecteurs de base du réseau réciproque :
[[ 1.72309382 -0.85365657  0.        ]
 [ 0.          1.92296174  0.        ]
 [-1.37559462 -0.85365662  1.03768591]]


In [7]:
reciprocal_lattice = lattice.reciprocal_lattice
print("Vecteurs du réseau réciproque :")
print(reciprocal_lattice.matrix)

Vecteurs du réseau réciproque :
[[ 5.46549812e-01 -1.63391134e+00 -8.54048969e-01]
 [ 5.46549812e-01  1.63391134e+00 -8.54048969e-01]
 [ 1.38006224e-03  0.00000000e+00  1.92296118e+00]]


 4. Identification du type de maille et du système cristallin  
    
On a trouvé que a = b = c = 6.055 Å et que alpha = beta = gamma = 37,029°. On est dans le cas ou a = b = c et alpha = beta = gamma ≠ 90°, c'est donc un système rhombohédrique. 
    
Et un réseau rhombohédrique fait toujours partie du système trigonal.

In [8]:
sga = SpacegroupAnalyzer(structure)

lattice_type = sga.get_lattice_type()
print("Type de maille :", lattice_type)

crystal_system = sga.get_crystal_system()
print("Système cristallin :", crystal_system)

Type de maille : rhombohedral
Système cristallin : trigonal


5. Détermination du groupe ponctuel 

Pour ce qui est du groupe ponctuel, on trouve que c'est -3m. Cela signifie qu'il possède un axe de rotation d'ordre 3 et qu'il
y a un plan miroir perpendiculaire à cet axe.



In [9]:
point_group = sga.get_point_group_symbol()
print("Groupe ponctuel :", point_group)

Groupe ponctuel : -3m
